language: cpp
sudo: false

branches:
  only:
    - master

linux64_addons:
    addons: &linux64
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - gcc-5
        - libboost-dev
        - libboost-filesystem1.54-dev

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
      addons: *linux64
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && COVERAGE=ON"
    # Using system libs
    - os: linux
      compiler: clang
      addons: *linux64
    - os: osx
      compiler: clang
      osx_image: xcode7.3
    - os: osx
      compiler: gcc
      osx_image: xcode7.3

before_install:
  # Setting environement
  - $CC --version
  - $CXX --version
  - pip install --user cpp-coveralls
  
script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - $CMAKE_CONFIGURE cmake $CMAKE_ARGS $CMAKE_EXTRA ..
  - make -j2
  - ctest -j2 --output-on-failure

after_success:
  - cd $TRAVIS_BUILD_DIR
  - |
    if [[ "${COVERAGE}" == "ON" ]]; then
        coveralls --gcov gcov-5 -e build/chemfiles -e build/chemfiles_build -e build/CHEMFILES-prefix -e build/CMakeFiles -E '.*external.*' --gcov-options '\-lp' --verbose
    fi
